name: 20 Deploy to Azure

on:
  workflow_dispatch:
  workflow_call:

jobs:
    deploy:
        environment: testing
        runs-on: ubuntu-latest
        steps: 
            - name: Check out the repository
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: | 
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                sudo apt install jq
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: daemonset
                path: daemonset.yaml
            - name: Install defender
              run: |
                az --version
                jq --version
                ls