name: 20 Deploy to Azure

on:
  workflow_dispatch:
  workflow_call:

jobs:
    defender:
        environment: testing
        runs-on: ubuntu-latest
        steps: 
            - name: Check out the repository
              uses: actions/checkout@v4