name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
  
jobs:
  defender:
    name: defender
    uses: ./.github/workflows/defender.yaml
    secrets: inherit 

  azure:
    needs: defender 
    name: azure
    uses: ./.github/workflows/azure.yaml
    secrets: inherit
